/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TopNavbar {
        /**
          * 左侧logo区域的展示
         */
        "logojson": string;
        /**
          * nav区域展示
         */
        "navjson": string;
    }
}
export interface TopNavbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTopNavbarElement;
}
declare global {
    interface HTMLTopNavbarElementEventMap {
        "menuNavClick": any;
        "chiNavClick": any;
        "thrNavClick": any;
    }
    interface HTMLTopNavbarElement extends Components.TopNavbar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTopNavbarElementEventMap>(type: K, listener: (this: HTMLTopNavbarElement, ev: TopNavbarCustomEvent<HTMLTopNavbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTopNavbarElementEventMap>(type: K, listener: (this: HTMLTopNavbarElement, ev: TopNavbarCustomEvent<HTMLTopNavbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTopNavbarElement: {
        prototype: HTMLTopNavbarElement;
        new (): HTMLTopNavbarElement;
    };
    interface HTMLElementTagNameMap {
        "top-navbar": HTMLTopNavbarElement;
    }
}
declare namespace LocalJSX {
    interface TopNavbar {
        /**
          * 左侧logo区域的展示
         */
        "logojson"?: string;
        /**
          * nav区域展示
         */
        "navjson"?: string;
        "onChiNavClick"?: (event: TopNavbarCustomEvent<any>) => void;
        "onMenuNavClick"?: (event: TopNavbarCustomEvent<any>) => void;
        "onThrNavClick"?: (event: TopNavbarCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "top-navbar": TopNavbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "top-navbar": LocalJSX.TopNavbar & JSXBase.HTMLAttributes<HTMLTopNavbarElement>;
        }
    }
}
